//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JQuery
{
    using System;
    using System.Collections.Generic;
    
    public partial class Persona
    {
        public Persona()
        {
            this.Autoes = new HashSet<Auto>();
        }
    
        public int per_id { get; set; }
        public string per_nombre { get; set; }
        public Nullable<int> per_edad { get; set; }
    
        public virtual ICollection<Auto> Autoes { get; set; }
    }
}
